### ISSUE TITLE
乘法表达式有问题

### ISSUE THREAD

**Issue by onlyhc** [nullne/evaluator#2]
func (f SuccessiveBinaryOperator) Eval(params ...interface{}) (interface{}, error) {
	if l := len(params); l < 2 {
		return 0.0, fmt.Errorf("SuccessiveBinaryOperator: need at leat two params, but got %d", l)
	}
	var res float64
	for _, p := range params {
		v, err := toFloat64(p)
		if err != nil {
			return 0.0, fmt.Errorf("SuccessiveBinaryOperator: %+v", err)
		}
		switch f.Mode {
		case ModeAdd:
			res += v
		case ModeMultiply:
			res *= v
		default:
			return 0.0, errors.New("SuccessiveBinaryOperator: only support add and multiply")
		}
	}
	return res, nil
}

如果是乘法时  res默认为0   无论乘什么都是0  需要在for循环前添加
if f.Mode==ModeMultiply{
		res=1
	}

**Comment by nullne** [comment]
thanks for pointing out, could you help to submit a pr also ? @onlyhc
